name: Remove markdown comments in PR
author: urlyy
description: remove markdown comments in GitHub PR body.

inputs:
  token:
    description: GitHub access token.
    required: true
runs:
  using: node20
  main: dist/index.js
  
branding:
  icon: align-left
  color: white
